### ISSUE TITLE
Browser remembers "E-mail" field instead of "Name" field for saving name

### ISSUE THREAD

**Issue by kaguy4** [Heyuri/kokonotsuba#106]
And for example if you make the browser remember "noko" for mail, if you enter "noko2" or "sage" for a post, it won't go in the first try and give a prompt about it instead, as shown below. So it should save the name field instead. It does already remember the password field properly.

![image](https://github.com/user-attachments/assets/84097ce9-75f9-41ad-ba6d-040feed99ab1)

**Comment by kaguy4** [comment]
At least my browser can remember multiple of mail fields, but it's still redundant to save all possible e-mail options and would be better off saving names
![image](https://github.com/user-attachments/assets/0da8b9b2-5953-43f5-9db8-9bbd30d5a402)

**Comment by k0me0** [comment]
Isn't this browser specific? The credentials are saved like this only because the browser thinks it's a login form because it has designated email and password fields, while the name gets saved by kokonotsuba using cookies.
If you type in a name you also get something like this:
![Screenshot 2024-07-30 154227](https://github.com/user-attachments/assets/15e9706b-652e-433b-8491-83ffc1faa20b)

**Comment by kaguy4** [comment]
Ah, then there is nothing to do
